In [7]:
import numpy as np
import random

In [3]:
district = np.arange(1,11,1)

In [6]:
force_draw = np.ceil(100/district)
num_votes_needed = np.sum(force_draw)
print(num_votes_needed)

296.0


In [9]:
random.sample(range(1,11),2)

[3, 1]

In [2]:
def f(n,s):
    if n == 1:
        yield (s,)
    else:
        for i in range(s + 1):
            for j in f(n - 1,s - i):
                yield (i,) + j


In [3]:

L = list(f(3,100))
print('total permutations:', len(L))

# First and last 10 of list
for i in L[:10] + L[-10:]:
    print(i)

total permutations: 5151
(0, 0, 100)
(0, 1, 99)
(0, 2, 98)
(0, 3, 97)
(0, 4, 96)
(0, 5, 95)
(0, 6, 94)
(0, 7, 93)
(0, 8, 92)
(0, 9, 91)
(97, 0, 3)
(97, 1, 2)
(97, 2, 1)
(97, 3, 0)
(98, 0, 2)
(98, 1, 1)
(98, 2, 0)
(99, 0, 1)
(99, 1, 0)
(100, 0, 0)


In [5]:
def compare(all_perms,num_district):
    

0

In [12]:
import numpy as np
L = np.array(L, dtype='int')
print(L)

[[  0   0 100]
 [  0   1  99]
 [  0   2  98]
 ..., 
 [ 99   0   1]
 [ 99   1   0]
 [100   0   0]]


In [45]:
compare = L*np.array([1,2,3])
compare[1]
cp = L

In [49]:
# test = (compare[1] < L) * 1
# print(test)
for idx, value in enumerate(compare[1]):
    if L[0][idx] < L[1][idx]:
        if compare[0][idx] < L[1][idx]:
            # cp[0][idx] = True
            print('True')
        else:
            # cp[0][idx] = False
            print('False')
compare[1]

array([  0,   2, 297])

In [37]:
compare[1]<L[0]

array([False, False, False], dtype=bool)

In [28]:
test[105]

array([1, 1, 0])

In [34]:
np.where(test.sum(axis=1) > 1)

(array([ 104,  105,  106, ..., 5139, 5140, 5144], dtype=int64),)